# Generated by Django 3.1.7 on 2021-03-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_date', models.DateTimeField(verbose_name='Дата документа')),
                ('Document_number', models.CharField(max_length=15, verbose_name='Номер')),
                ('Document_author', models.CharField(max_length=40, verbose_name='Автор')),
                ('Document_viewmovement', models.CharField(max_length=15, verbose_name='Вид движения')),
                ('Document_comment', models.CharField(max_length=40, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='TableProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableProducts_nomenclature', models.CharField(max_length=40, verbose_name='Автор')),
                ('TableProducts_quantity', models.CharField(max_length=15, verbose_name='Количество')),
                ('TableProducts_price', models.CharField(max_length=15, verbose_name='Цена')),
                ('TableProducts_sum', models.CharField(max_length=15, verbose_name='Сумма')),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidocuments.document')),
            ],
        ),
    ]
