# Generated by Django 3.1.7 on 2021-03-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidocuments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='tableproducts',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.AlterField(
            model_name='tableproducts',
            name='TableProducts_nomenclature',
            field=models.CharField(max_length=40, verbose_name='Номенклатура'),
        ),
    ]
