# Generated by Django 3.1.7 on 2021-03-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidocuments', '0003_document_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_viewmovement',
            field=models.CharField(max_length=20, verbose_name='Вид движения'),
        ),
    ]
